export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  author: "stephanie" | "richard" | "team";
  category: string;
  tags: string[];
  readingTime: number;
  tocItems: { id: string; label: string }[];
  tocItemsNl?: { id: string; label: string }[];
  softCta: "checklist" | "case-study" | "discovery" | "template";
  faqItems?: { q: string; a: string }[];
  image?: string;
  hidden?: boolean;
};

const _allBlogPosts: BlogPost[] = [
  {
    slug: "procurement-data-cost",
    image: "/images/blog/procurement-data-cost.jpg",
    title: "Why Your Procurement Data Is Costing You More Than You Think",
    description: "Poor procurement data quality costs hard services companies 1-3% of total spend per year. This article shows where the cost hides and how to fix it.",
    publishedAt: "2026-02-04",
    author: "stephanie",
    category: "Procurement",
    tags: ["procurement data quality", "spend analytics", "UNSPSC", "category management"],
    readingTime: 7,
    tocItems: [
      { id: "the-problem", label: "The problem with procurement data" },
      { id: "where-cost-hides", label: "Where the cost hides" },
      { id: "what-clean-data-enables", label: "What clean data enables" },
      { id: "the-process", label: "How the fix works" },
    ],
    tocItemsNl: [
      { id: "the-problem", label: "Het probleem met procurement data" },
      { id: "where-cost-hides", label: "Waar de kosten verborgen zitten" },
      { id: "what-clean-data-enables", label: "Wat schone data mogelijk maakt" },
      { id: "the-process", label: "Hoe de oplossing werkt" },
    ],
    softCta: "case-study",
  },
  {
    slug: "what-is-unspsc",
    image: "/images/blog/what-is-unspsc.jpg",
    title: "What Is UNSPSC — And Why Hard Services Companies Should Care",
    description: "UNSPSC is the global procurement classification standard. This guide explains the hierarchy, why ERP systems don't solve classification on their own, and how automated classification works at scale.",
    publishedAt: "2026-02-17",
    author: "team",
    category: "Procurement",
    tags: ["UNSPSC", "procurement classification", "spend data", "ERP"],
    readingTime: 8,
    tocItems: [
      { id: "what-is-unspsc", label: "What UNSPSC is" },
      { id: "why-it-matters", label: "Why it matters in practice" },
      { id: "erp-problem", label: "Why ERPs don't solve this" },
      { id: "what-it-unlocks", label: "What classification unlocks" },
      { id: "maintaining", label: "Maintaining classification" },
    ],
    tocItemsNl: [
      { id: "what-is-unspsc", label: "Wat UNSPSC is" },
      { id: "why-it-matters", label: "Waarom het in de praktijk belangrijk is" },
      { id: "erp-problem", label: "Waarom ERP's dit niet oplossen" },
      { id: "what-it-unlocks", label: "Wat classificatie mogelijk maakt" },
      { id: "maintaining", label: "Classificatie onderhouden" },
    ],
    softCta: "template",
  },
  {
    slug: "asset-register-problems",
    image: "/images/blog/asset-register-problems.jpg",
    title: "The Real Reason Your Asset Register Isn't Working",
    description: "Most FM companies have an asset register. Most don't trust it. This article explains the specific data gaps, their financial cost, and how AI-assisted enrichment fixes them.",
    publishedAt: "2026-02-24",
    author: "richard",
    category: "Asset Management",
    tags: ["asset register", "asset data management", "facilities management", "predictive maintenance"],
    readingTime: 7,
    tocItems: [
      { id: "what-bad-looks-like", label: "What a failing register looks like" },
      { id: "financial-cost", label: "The financial cost" },
      { id: "what-it-enables", label: "What accuracy enables" },
      { id: "missing-data", label: "What is typically missing" },
      { id: "ongoing-maintenance", label: "Ongoing maintenance" },
    ],
    tocItemsNl: [
      { id: "what-bad-looks-like", label: "Hoe een falend register eruitziet" },
      { id: "financial-cost", label: "De financiële kosten" },
      { id: "what-it-enables", label: "Wat nauwkeurigheid mogelijk maakt" },
      { id: "missing-data", label: "Wat er typisch ontbreekt" },
      { id: "ongoing-maintenance", label: "Doorlopend onderhoud" },
    ],
    softCta: "discovery",
  },
  {
    slug: "category-management-kraljic-hard-fm",
    image: "/images/blog/category-management-kraljic-hard-fm.jpg",
    title: "The Kraljic Matrix, Category Management, and Why Your Data Is the Missing Piece",
    description: "The Kraljic Matrix is the most useful tool in procurement strategy but it requires clean spend data to work. This article applies it to hard FM, construction, and MRO.",
    publishedAt: "2026-03-06",
    author: "stephanie",
    category: "Procurement",
    tags: ["category management", "Kraljic matrix", "hard FM procurement", "spend visibility"],
    readingTime: 9,
    tocItems: [
      { id: "kraljic", label: "The Kraljic Matrix explained" },
      { id: "data-problem", label: "Why data is the blocker" },
      { id: "five-scenarios", label: "5 category scenarios" },
      { id: "data-as-fuel", label: "Data as category management fuel" },
    ],
    tocItemsNl: [
      { id: "kraljic", label: "De Kraljic Matrix uitgelegd" },
      { id: "data-problem", label: "Waarom data de blokkade is" },
      { id: "five-scenarios", label: "5 categoriescenario's" },
      { id: "data-as-fuel", label: "Data als brandstof voor category management" },
    ],
    softCta: "case-study",
  },
  {
    slug: "ai-readiness-data-quality",
    image: "/images/blog/ai-readiness-data-quality.jpg",
    title: "AI Readiness Isn't an IT Problem. It's a Data Problem.",
    description: "AI tools amplify whatever structure exists in your data. If your procurement and asset data is messy, AI makes it expensively wrong. Here is what readiness actually requires.",
    publishedAt: "2026-03-18",
    author: "stephanie",
    category: "AI & Digital",
    tags: ["AI readiness", "Microsoft Fabric", "data quality", "digital transformation"],
    readingTime: 8,
    tocItems: [
      { id: "what-ai-requires", label: "What AI tools require" },
      { id: "fabric-reality", label: "The Microsoft Fabric reality" },
      { id: "checklist", label: "AI readiness checklist" },
      { id: "preparation", label: "What preparation looks like" },
    ],
    tocItemsNl: [
      { id: "what-ai-requires", label: "Wat AI-tools vereisen" },
      { id: "fabric-reality", label: "De Microsoft Fabric-realiteit" },
      { id: "checklist", label: "AI-gereedheidscontrolelijst" },
      { id: "preparation", label: "Hoe voorbereiding eruitziet" },
    ],
    softCta: "checklist",
    faqItems: [
      { q: "What does AI readiness mean for a hard services company?", a: "AI readiness means your procurement and asset data is consistently structured, classified, and validated so that AI platforms can produce reliable outputs rather than amplifying the inconsistencies in your data." },
      { q: "Does Microsoft Fabric fix data quality issues automatically?", a: "No. Microsoft Fabric inherits the structure of the data you load into it. Without a clean data foundation, Fabric deployments typically spend their first phase on remediation rather than value creation." },
      { q: "How long does it take to get data AI-ready?", a: "A baseline assessment and initial cleaning typically takes four to six weeks. Ongoing quality control is then automated, so the data stays AI-ready without recurring manual effort." },
    ],
  },
  {
    slug: "fm-tender-win-rate",
    image: "/images/blog/fm-tender-win-rate.jpg",
    title: "How to Win More FM Tenders Without Increasing Your Team",
    description: "Most FM tender losses come down to pricing confidence, not capability. Clean cost data changes bid accuracy, speed, and win rate without adding headcount.",
    publishedAt: "2026-03-27",
    author: "richard",
    category: "Commercial FM",
    tags: ["FM tenders", "bid pricing", "facilities management", "procurement data"],
    readingTime: 8,
    tocItems: [
      { id: "pricing-problem", label: "The pricing confidence problem" },
      { id: "two-scenarios", label: "Scenario A vs B" },
      { id: "what-slows", label: "What slows bid teams down" },
      { id: "what-changes", label: "What changes with clean data" },
      { id: "compounding", label: "The compounding effect" },
    ],
    tocItemsNl: [
      { id: "pricing-problem", label: "Het prijsvertrouwensprobleem" },
      { id: "two-scenarios", label: "Scenario A vs B" },
      { id: "what-slows", label: "Wat aanbestedingsteams vertraagt" },
      { id: "what-changes", label: "Wat verandert met schone data" },
      { id: "compounding", label: "Het cumulatieve effect" },
    ],
    softCta: "discovery",
  },
  {
    slug: "excel-heroics-hard-services",
    image: "/images/blog/excel-heroics-hard-services.jpg",
    title: "The Hidden Cost of Excel Heroics in Hard Services",
    description: "Every hard services company has someone who knows the data. This article explains the operational risk they carry, what it costs, and what the migration away from manual data management looks like.",
    publishedAt: "2026-04-03",
    author: "team",
    category: "Data Management",
    tags: ["data management", "manual reporting", "procurement automation", "operational risk"],
    readingTime: 7,
    tocItems: [
      { id: "visible-cost", label: "Visible vs real cost" },
      { id: "diagnostic", label: "Are you in Excel heroics territory?" },
      { id: "migration", label: "What the migration looks like" },
      { id: "other-side", label: "What the other side looks like" },
    ],
    tocItemsNl: [
      { id: "visible-cost", label: "Zichtbare vs werkelijke kosten" },
      { id: "diagnostic", label: "Zit u in het Excel-heldenterritorium?" },
      { id: "migration", label: "Hoe de migratie eruitziet" },
      { id: "other-side", label: "Hoe de andere kant eruitziet" },
    ],
    softCta: "template",
  },
  {
    slug: "construction-procurement-material-costs",
    image: "/images/blog/construction-procurement-material-costs.jpg",
    title: "Construction Procurement Data: Why Your Material Costs Are Harder to Control Than You Think",
    description: "Construction spend is structurally fragmented across projects. This article explains why material cost control requires spend classification and what steel procurement looks like as a case study.",
    publishedAt: "2026-04-14",
    author: "richard",
    category: "Construction",
    tags: ["construction procurement", "material costs", "spend classification", "supplier consolidation"],
    readingTime: 8,
    tocItems: [
      { id: "structural-problem", label: "Why construction data is different" },
      { id: "steel-case-study", label: "Steel: a case study" },
      { id: "spec-standardisation", label: "Specification standardisation" },
      { id: "software-integration", label: "Integration with construction software" },
    ],
    tocItemsNl: [
      { id: "structural-problem", label: "Waarom bouwdata anders is" },
      { id: "steel-case-study", label: "Staal: een casestudy" },
      { id: "spec-standardisation", label: "Specificatiestandardisatie" },
      { id: "software-integration", label: "Integratie met bouwsoftware" },
    ],
    softCta: "case-study",
  },
  {
    slug: "what-clean-data-enables",
    image: "/images/blog/what-clean-data-enables.jpg",
    title: "What Happens When Your Data Is Finally Clean: 5 Things That Become Possible",
    description: "Five specific capabilities that open up when procurement and asset data is clean, classified, and consistently maintained with practical examples of what each looks like.",
    publishedAt: "2026-04-28",
    author: "stephanie",
    category: "Procurement",
    tags: ["procurement data quality", "asset management", "AI readiness", "tender pricing"],
    readingTime: 8,
    tocItems: [
      { id: "supplier-consolidation", label: "1. Supplier consolidation" },
      { id: "predictive-maintenance", label: "2. Predictive maintenance" },
      { id: "tender-pricing", label: "3. Accurate tender pricing" },
      { id: "ai-tools", label: "4. AI tools that deliver" },
      { id: "strategic-procurement", label: "5. Strategic procurement" },
    ],
    tocItemsNl: [
      { id: "supplier-consolidation", label: "1. Leveranciersconsolidatie" },
      { id: "predictive-maintenance", label: "2. Voorspellend onderhoud" },
      { id: "tender-pricing", label: "3. Nauwkeurige aanbestedingsprijzen" },
      { id: "ai-tools", label: "4. AI-tools die leveren" },
      { id: "strategic-procurement", label: "5. Strategische inkoop" },
    ],
    softCta: "case-study",
  },
  {
    slug: "unspsc-vs-eclass-vs-cpv",
    image: "/images/blog/unspsc-vs-eclass-vs-cpv.jpg",
    title: "UNSPSC vs. eClass vs. CPV: Which Classification Standard Is Right for Your Business?",
    description: "A clear breakdown of the three main procurement classification standards UNSPSC, eClass, and CPV with a practical guide to implementation at scale.",
    publishedAt: "2026-05-07",
    author: "team",
    category: "Procurement",
    tags: ["UNSPSC", "eClass", "CPV", "procurement classification", "spend standards"],
    readingTime: 9,
    tocItems: [
      { id: "unspsc", label: "UNSPSC" },
      { id: "eclass", label: "eClass" },
      { id: "cpv", label: "CPV" },
      { id: "which-to-use", label: "Which to use" },
      { id: "implementation", label: "Implementation reality" },
    ],
    tocItemsNl: [
      { id: "unspsc", label: "UNSPSC" },
      { id: "eclass", label: "eClass" },
      { id: "cpv", label: "CPV" },
      { id: "which-to-use", label: "Welke te gebruiken" },
      { id: "implementation", label: "Implementatierealiteit" },
    ],
    softCta: "discovery",
    faqItems: [
      { q: "What is the difference between UNSPSC and eClass?", a: "UNSPSC is a global four-level taxonomy covering all products and services, best for spend analytics and category management. eClass includes product attribute definitions alongside codes, making it more precise for industrial and engineering master data." },
      { q: "Do I need to use CPV codes for private sector procurement?", a: "No. CPV is mandated only for EU public procurement notices. Private sector organisations should use UNSPSC or eClass for internal spend management." },
      { q: "How many UNSPSC codes are there?", a: "The UNSPSC taxonomy contains over 55,000 commodity codes across four levels: Segment, Family, Class, and Commodity. It is updated quarterly by GS1 US on behalf of the United Nations." },
    ],
  },
  {
    slug: "unspsc-classification-sap",
    image: "/images/blog/unspsc-classification-sap.jpg",
    title: "How to Implement UNSPSC Classification in SAP",
    description: "A practical guide to automating UNSPSC coding in SAP-based procurement environments — what works, what does not, and how to get from messy spend data to a clean category baseline.",
    publishedAt: "2026-04-14",
    author: "team",
    category: "Procurement",
    tags: ["UNSPSC", "SAP", "procurement data quality", "spend classification"],
    readingTime: 8,
    tocItems: [
      { id: "sap-problem", label: "The SAP problem nobody talks about" },
      { id: "three-approaches", label: "Three approaches to UNSPSC in SAP" },
      { id: "what-to-export", label: "What data to export from SAP" },
      { id: "good-classification", label: "What good classification looks like" },
      { id: "review-queue", label: "The review queue" },
      { id: "timing", label: "Timing" },
    ],
    tocItemsNl: [
      { id: "sap-problem", label: "Het SAP-probleem waar niemand over spreekt" },
      { id: "three-approaches", label: "Drie benaderingen van UNSPSC in SAP" },
      { id: "what-to-export", label: "Welke data uit SAP te exporteren" },
      { id: "good-classification", label: "Hoe goede classificatie eruitziet" },
      { id: "review-queue", label: "De reviewwachtrij" },
      { id: "timing", label: "Timing" },
    ],
    softCta: "discovery",
  },
  {
    slug: "unspsc-classification-accuracy",
    image: "/images/blog/unspsc-classification-accuracy.jpg",
    title: "UNSPSC Classification Accuracy: What 90–95% Actually Means",
    description: "What does 90–95% automated UNSPSC classification accuracy mean in practice? How is it measured, what does the remaining 5–10% look like, and how does accuracy improve over time?",
    publishedAt: "2026-04-28",
    author: "team",
    category: "Procurement",
    tags: ["UNSPSC", "procurement data quality", "classification accuracy", "data quality"],
    readingTime: 6,
    tocItems: [
      { id: "the-number", label: "The number you keep seeing" },
      { id: "how-measured", label: "How accuracy is defined" },
      { id: "hard-items", label: "What makes an item hard to classify" },
      { id: "accuracy-stages", label: "Accuracy at different stages" },
      { id: "four-layer", label: "How the four-layer engine works" },
      { id: "downstream", label: "What accuracy actually buys you" },
    ],
    tocItemsNl: [
      { id: "the-number", label: "Het getal dat u blijft zien" },
      { id: "how-measured", label: "Hoe nauwkeurigheid wordt gedefinieerd" },
      { id: "hard-items", label: "Wat een item moeilijk te classificeren maakt" },
      { id: "accuracy-stages", label: "Nauwkeurigheid in verschillende fasen" },
      { id: "four-layer", label: "Hoe de vierlaagsmotor werkt" },
      { id: "downstream", label: "Wat nauwkeurigheid u oplevert" },
    ],
    softCta: "discovery",
    faqItems: [
      { q: "What does 90–95% auto-classification mean?", a: "It means 90–95% of procurement line items are assigned a UNSPSC commodity code by the automated engine without any human input. The remaining 5–10% are flagged for human review." },
      { q: "How is UNSPSC accuracy measured?", a: "Accuracy is measured at commodity level — the most specific level of the UNSPSC hierarchy (8-digit code). Measuring at segment or family level would produce higher numbers but less useful classification." },
      { q: "Does accuracy improve over time?", a: "Yes. Every human review decision feeds back into the ML model. After 3 months of operation, auto-classification typically rises to 90–95%. After 12 months, it often exceeds 95% as the model learns from your team's decisions." },
    ],
  },
  {
    slug: "unspsc-for-mro",
    image: "/images/blog/unspsc-for-mro.jpg",
    title: "UNSPSC for MRO: Classifying Maintenance, Repair, and Operations Spend",
    description: "MRO procurement is the hardest category to classify consistently. Here is why UNSPSC works for maintenance spend, and what it takes to get clean MRO data from SAP or Maximo.",
    publishedAt: "2026-05-05",
    author: "richard",
    category: "Procurement",
    tags: ["UNSPSC", "MRO", "procurement data quality", "asset management", "maintenance"],
    readingTime: 7,
    tocItems: [
      { id: "why-hard", label: "Why MRO spend is the hardest to classify" },
      { id: "segments", label: "UNSPSC segments for MRO" },
      { id: "vs-mpn", label: "UNSPSC vs manufacturer part numbers" },
      { id: "how-it-works", label: "How automated MRO classification works" },
      { id: "enrichment", label: "Enriching to part number level" },
      { id: "downstream", label: "The downstream value" },
    ],
    tocItemsNl: [
      { id: "why-hard", label: "Waarom MRO-spend het moeilijkst te classificeren is" },
      { id: "segments", label: "UNSPSC-segmenten voor MRO" },
      { id: "vs-mpn", label: "UNSPSC vs fabrikantonderdeelnummers" },
      { id: "how-it-works", label: "Hoe geautomatiseerde MRO-classificatie werkt" },
      { id: "enrichment", label: "Verrijken tot onderdeelnummerniveau" },
      { id: "downstream", label: "De neerwaartse waarde" },
    ],
    softCta: "discovery",
  },
  {
    slug: "unspsc-category-management",
    image: "/images/blog/unspsc-category-management.jpg",
    title: "The Category Management Problem No One Talks About: Why You Need UNSPSC Spend Classification",
    description: "Category management in FM and infrastructure fails without commodity-level spend data. Learn how UNSPSC classification transforms unstructured invoice data into actionable procurement strategy.",
    publishedAt: "2026-05-18",
    author: "team",
    category: "Procurement",
    tags: ["UNSPSC", "Category Management", "FM", "Infrastructure", "Spend Analysis"],
    readingTime: 7,
    tocItems: [
      { id: "the-category-management-problem", label: "The category management problem" },
      { id: "what-unspsc-makes-possible", label: "What UNSPSC makes possible" },
      { id: "before-after", label: "Before and after: a real example" },
      { id: "where-to-start", label: "Where to start" },
    ],
    tocItemsNl: [
      { id: "the-category-management-problem", label: "Het category management-probleem" },
      { id: "what-unspsc-makes-possible", label: "Wat UNSPSC mogelijk maakt" },
      { id: "before-after", label: "Voor en na: een echt voorbeeld" },
      { id: "where-to-start", label: "Waar te beginnen" },
    ],
    softCta: "discovery",
  },
  {
    slug: "maverick-spend-unspsc",
    image: "/images/blog/maverick-spend-unspsc.jpg",
    title: "How to Control Maverick Spend: Why It's a Data Problem, Not a Discipline Problem",
    description: "Discover why maverick spend in FM and construction is a data visibility issue, and how commodity-level UNSPSC classification can uncover hidden procurement savings.",
    publishedAt: "2026-05-18",
    author: "team",
    category: "Procurement",
    tags: ["UNSPSC", "Maverick Spend", "Procurement", "MRO", "FM", "Spend Control"],
    readingTime: 7,
    tocItems: [
      { id: "maverick-spend-is-not-a-discipline-problem", label: "Not a discipline problem" },
      { id: "what-gets-exposed", label: "What gets exposed" },
      { id: "the-golden-500", label: "The Golden 500 SKU approach" },
      { id: "the-mro-case", label: "The MRO case" },
    ],
    tocItemsNl: [
      { id: "maverick-spend-is-not-a-discipline-problem", label: "Geen disciplineprobleem" },
      { id: "what-gets-exposed", label: "Wat wordt blootgelegd" },
      { id: "the-golden-500", label: "De Gouden 500 SKU-aanpak" },
      { id: "the-mro-case", label: "De MRO-casus" },
    ],
    softCta: "discovery",
  },
  {
    slug: "win-ai-race-procurement-data-quality",
    image: "/images/blog/win-ai-race-procurement-data-quality.jpg",
    title: "How to Win the AI Race in Procurement: Start with Clean Data",
    description: "AI in procurement only works when your data is clean, classified, and trusted. Learn how Pearstop helps hard services teams turn procurement and asset data into an AI-ready advantage.",
    publishedAt: "2026-06-11",
    author: "team",
    category: "AI & Digital",
    tags: ["AI readiness", "procurement data quality", "data classification", "digital transformation"],
    readingTime: 9,
    tocItems: [
      { id: "the-problem-is-not-lack-of-data", label: "The problem is not lack of data" },
      { id: "ai-readiness-is-a-procurement-issue", label: "AI readiness is a procurement issue" },
      { id: "what-pearstop-does", label: "What Pearstop does" },
      { id: "why-classification-matters", label: "Why classification matters" },
      { id: "human-in-control-automation", label: "Human-in-control automation" },
      { id: "how-to-win-the-ai-race", label: "How to win the AI race" },
    ],
    tocItemsNl: [
      { id: "the-problem-is-not-lack-of-data", label: "Het probleem is niet een gebrek aan data" },
      { id: "ai-readiness-is-a-procurement-issue", label: "AI-gereedheid is een procurement-vraagstuk" },
      { id: "what-pearstop-does", label: "Wat Pearstop doet" },
      { id: "why-classification-matters", label: "Waarom classificatie belangrijk is" },
      { id: "human-in-control-automation", label: "Mens-in-controle-automatisering" },
      { id: "how-to-win-the-ai-race", label: "Hoe de AI-race te winnen" },
    ],
    softCta: "discovery",
  },
  {
    slug: "procurement-data-readiness-ai",
    image: "/images/blog/procurement-data-readiness-ai.jpg",
    title: "What Is Procurement Data Readiness, and Why Does It Matter for AI?",
    description: "Procurement data readiness is the foundation of AI in procurement. Learn what it means, why data quality matters, and how Pearstop helps hard services teams get AI-ready.",
    publishedAt: "2026-06-11",
    author: "team",
    category: "AI & Digital",
    tags: ["AI readiness", "procurement data quality", "data readiness", "digital transformation"],
    readingTime: 8,
    tocItems: [
      { id: "why-procurement-data-is-often-difficult-to-use", label: "Why procurement data is difficult to use" },
      { id: "what-does-clean-procurement-data-look-like", label: "What clean procurement data looks like" },
      { id: "how-pearstop-supports-procurement-data-readiness", label: "How Pearstop supports data readiness" },
      { id: "why-ai-in-procurement-depends-on-data-quality", label: "Why AI depends on data quality" },
      { id: "how-organisations-can-win-the-ai-race-in-procurement", label: "How to win the AI race" },
      { id: "the-future-of-procurement-is-ai-ready-data", label: "The future of procurement" },
    ],
    tocItemsNl: [
      { id: "why-procurement-data-is-often-difficult-to-use", label: "Waarom procurement data moeilijk te gebruiken is" },
      { id: "what-does-clean-procurement-data-look-like", label: "Hoe schone procurement data eruitziet" },
      { id: "how-pearstop-supports-procurement-data-readiness", label: "Hoe Pearstop data readiness ondersteunt" },
      { id: "why-ai-in-procurement-depends-on-data-quality", label: "Waarom AI afhankelijk is van datakwaliteit" },
      { id: "how-organisations-can-win-the-ai-race-in-procurement", label: "Hoe de AI-race te winnen" },
      { id: "the-future-of-procurement-is-ai-ready-data", label: "De toekomst van procurement" },
    ],
    softCta: "discovery",
  },
  {
    slug: "datore-vs-pearstop",
    title: "Datore vs Pearstop: Two Different Ways to Turn Messy Business Data into Action",
    description: "Datore and Pearstop both help businesses in the built environment tackle messy operational data — but from different angles. Here is how they compare and where each one fits.",
    publishedAt: "2026-06-19",
    author: "team",
    category: "Data Quality",
    tags: ["data quality", "procurement data", "facilities management", "built environment", "data strategy"],
    readingTime: 6,
    tocItems: [
      { id: "what-datore-does", label: "What Datore does" },
      { id: "what-pearstop-does", label: "What Pearstop does" },
      { id: "datores-strength-is-breadth", label: "Datore's strength is breadth" },
      { id: "pearstops-strength-is-depth", label: "Pearstop's strength is depth" },
      { id: "where-they-sit-in-the-data-value-chain", label: "Where they sit in the data value chain" },
      { id: "how-to-choose", label: "How to choose" },
      { id: "two-complementary-layers-of-the-same-journey", label: "Two complementary layers" },
    ],
    softCta: "discovery",
    hidden: true,
  },
];

export const blogPosts: BlogPost[] = _allBlogPosts.filter((p) => !p.hidden);

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
