export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  category: string;
  tags: string[];
  readingTime: number;
  tocItems: { id: string; label: string }[];
  tocItemsNl?: { id: string; label: string }[];
  softCta: "checklist" | "case-study" | "discovery" | "template";
  faqItems?: { q: string; a: string }[];
  image?: string;
  hidden?: boolean;
};

const _allBlogPosts: BlogPost[] = [
  {
    slug: "procurement-data-cost",
    image: "/images/blog/procurement-data-cost.jpg",
    title: "Why Your Procurement Data Is Costing You More Than You Think",
    description: "Poor procurement data quality costs hard services companies 1-3% of total spend per year. This article shows where the cost hides and how to fix it.",
    publishedAt: "2026-02-04",
    category: "Procurement",
    tags: ["procurement data quality", "spend analytics", "UNSPSC", "category management"],
    readingTime: 7,
    tocItems: [
      { id: "the-problem", label: "The problem with procurement data" },
      { id: "where-cost-hides", label: "Where the cost hides" },
      { id: "what-clean-data-enables", label: "What clean data enables" },
      { id: "the-process", label: "How the fix works" },
    ],
    tocItemsNl: [
      { id: "the-problem", label: "Het probleem met procurement data" },
      { id: "where-cost-hides", label: "Waar de kosten verborgen zitten" },
      { id: "what-clean-data-enables", label: "Wat schone data mogelijk maakt" },
      { id: "the-process", label: "Hoe de oplossing werkt" },
    ],
    softCta: "case-study",
  },
  {
    slug: "what-is-unspsc",
    image: "/images/blog/what-is-unspsc.jpg",
    title: "What Is UNSPSC — And Why Hard Services Companies Should Care",
    description: "UNSPSC is the global procurement classification standard. This guide explains the hierarchy, why ERP systems don't solve classification on their own, and how automated classification works at scale.",
    publishedAt: "2026-02-17",
    category: "Procurement",
    tags: ["UNSPSC", "procurement classification", "spend data", "ERP"],
    readingTime: 8,
    tocItems: [
      { id: "what-is-unspsc", label: "What UNSPSC is" },
      { id: "why-it-matters", label: "Why it matters in practice" },
      { id: "erp-problem", label: "Why ERPs don't solve this" },
      { id: "what-it-unlocks", label: "What classification unlocks" },
      { id: "maintaining", label: "Maintaining classification" },
    ],
    tocItemsNl: [
      { id: "what-is-unspsc", label: "Wat UNSPSC is" },
      { id: "why-it-matters", label: "Waarom het in de praktijk belangrijk is" },
      { id: "erp-problem", label: "Waarom ERP's dit niet oplossen" },
      { id: "what-it-unlocks", label: "Wat classificatie mogelijk maakt" },
      { id: "maintaining", label: "Classificatie onderhouden" },
    ],
    softCta: "template",
  },
  {
    slug: "asset-register-problems",
    image: "/images/blog/asset-register-problems.jpg",
    title: "The Real Reason Your Asset Register Isn't Working",
    description: "Most FM companies have an asset register. Most don't trust it. This article explains the specific data gaps, their financial cost, and how AI-assisted enrichment fixes them.",
    publishedAt: "2026-02-24",
    category: "Asset Management",
    tags: ["asset register", "asset data management", "facilities management", "predictive maintenance"],
    readingTime: 7,
    tocItems: [
      { id: "what-bad-looks-like", label: "What a failing register looks like" },
      { id: "financial-cost", label: "The financial cost" },
      { id: "what-it-enables", label: "What accuracy enables" },
      { id: "missing-data", label: "What is typically missing" },
      { id: "ongoing-maintenance", label: "Ongoing maintenance" },
    ],
    tocItemsNl: [
      { id: "what-bad-looks-like", label: "Hoe een falend register eruitziet" },
      { id: "financial-cost", label: "De financiële kosten" },
      { id: "what-it-enables", label: "Wat nauwkeurigheid mogelijk maakt" },
      { id: "missing-data", label: "Wat er typisch ontbreekt" },
      { id: "ongoing-maintenance", label: "Doorlopend onderhoud" },
    ],
    softCta: "discovery",
  },
  {
    slug: "category-management-kraljic-hard-fm",
    image: "/images/blog/category-management-kraljic-hard-fm.jpg",
    title: "The Kraljic Matrix, Category Management, and Why Your Data Is the Missing Piece",
    description: "The Kraljic Matrix is the most useful tool in procurement strategy but it requires clean spend data to work. This article applies it to hard FM, construction, and MRO.",
    publishedAt: "2026-03-06",
    category: "Procurement",
    tags: ["category management", "Kraljic matrix", "hard FM procurement", "spend visibility"],
    readingTime: 9,
    tocItems: [
      { id: "kraljic", label: "The Kraljic Matrix explained" },
      { id: "data-problem", label: "Why data is the blocker" },
      { id: "five-scenarios", label: "5 category scenarios" },
      { id: "data-as-fuel", label: "Data as category management fuel" },
    ],
    tocItemsNl: [
      { id: "kraljic", label: "De Kraljic Matrix uitgelegd" },
      { id: "data-problem", label: "Waarom data de blokkade is" },
      { id: "five-scenarios", label: "5 categoriescenario's" },
      { id: "data-as-fuel", label: "Data als brandstof voor category management" },
    ],
    softCta: "case-study",
  },
  {
    slug: "ai-readiness-data-quality",
    image: "/images/blog/ai-readiness-data-quality.jpg",
    title: "AI Readiness Isn't an IT Problem. It's a Data Problem.",
    description: "AI tools amplify whatever structure exists in your data. If your procurement and asset data is messy, AI makes it expensively wrong. Here is what readiness actually requires.",
    publishedAt: "2026-03-18",
    category: "AI & Digital",
    tags: ["AI readiness", "Microsoft Fabric", "data quality", "digital transformation"],
    readingTime: 8,
    tocItems: [
      { id: "what-ai-requires", label: "What AI tools require" },
      { id: "fabric-reality", label: "The Microsoft Fabric reality" },
      { id: "checklist", label: "AI readiness checklist" },
      { id: "preparation", label: "What preparation looks like" },
    ],
    tocItemsNl: [
      { id: "what-ai-requires", label: "Wat AI-tools vereisen" },
      { id: "fabric-reality", label: "De Microsoft Fabric-realiteit" },
      { id: "checklist", label: "AI-gereedheidscontrolelijst" },
      { id: "preparation", label: "Hoe voorbereiding eruitziet" },
    ],
    softCta: "checklist",
    faqItems: [
      { q: "What does AI readiness mean for a hard services company?", a: "AI readiness means your procurement and asset data is consistently structured, classified, and validated so that AI platforms can produce reliable outputs rather than amplifying the inconsistencies in your data." },
      { q: "Does Microsoft Fabric fix data quality issues automatically?", a: "No. Microsoft Fabric inherits the structure of the data you load into it. Without a clean data foundation, Fabric deployments typically spend their first phase on remediation rather than value creation." },
      { q: "How long does it take to get data AI-ready?", a: "A baseline assessment and initial cleaning typically takes four to six weeks. Ongoing quality control is then automated, so the data stays AI-ready without recurring manual effort." },
    ],
  },
  {
    slug: "fm-tender-win-rate",
    image: "/images/blog/fm-tender-win-rate.jpg",
    title: "How to Win More FM Tenders Without Increasing Your Team",
    description: "Most FM tender losses come down to pricing confidence, not capability. Clean cost data changes bid accuracy, speed, and win rate without adding headcount.",
    publishedAt: "2026-03-27",
    category: "Commercial FM",
    tags: ["FM tenders", "bid pricing", "facilities management", "procurement data"],
    readingTime: 8,
    tocItems: [
      { id: "pricing-problem", label: "The pricing confidence problem" },
      { id: "two-scenarios", label: "Scenario A vs B" },
      { id: "what-slows", label: "What slows bid teams down" },
      { id: "what-changes", label: "What changes with clean data" },
      { id: "compounding", label: "The compounding effect" },
    ],
    tocItemsNl: [
      { id: "pricing-problem", label: "Het prijsvertrouwensprobleem" },
      { id: "two-scenarios", label: "Scenario A vs B" },
      { id: "what-slows", label: "Wat aanbestedingsteams vertraagt" },
      { id: "what-changes", label: "Wat verandert met schone data" },
      { id: "compounding", label: "Het cumulatieve effect" },
    ],
    softCta: "discovery",
  },
  {
    slug: "excel-heroics-hard-services",
    image: "/images/blog/excel-heroics-hard-services.jpg",
    title: "The Hidden Cost of Excel Heroics in Hard Services",
    description: "Every hard services company has someone who knows the data. This article explains the operational risk they carry, what it costs, and what the migration away from manual data management looks like.",
    publishedAt: "2026-04-03",
    category: "Data Management",
    tags: ["data management", "manual reporting", "procurement automation", "operational risk"],
    readingTime: 7,
    tocItems: [
      { id: "visible-cost", label: "Visible vs real cost" },
      { id: "diagnostic", label: "Are you in Excel heroics territory?" },
      { id: "migration", label: "What the migration looks like" },
      { id: "other-side", label: "What the other side looks like" },
    ],
    tocItemsNl: [
      { id: "visible-cost", label: "Zichtbare vs werkelijke kosten" },
      { id: "diagnostic", label: "Zit u in het Excel-heldenterritorium?" },
      { id: "migration", label: "Hoe de migratie eruitziet" },
      { id: "other-side", label: "Hoe de andere kant eruitziet" },
    ],
    softCta: "template",
  },
  {
    slug: "construction-procurement-material-costs",
    image: "/images/blog/construction-procurement-material-costs.jpg",
    title: "Construction Procurement Data: Why Your Material Costs Are Harder to Control Than You Think",
    description: "Construction spend is structurally fragmented across projects. This article explains why material cost control requires spend classification and what steel procurement looks like as a case study.",
    publishedAt: "2026-04-14",
    category: "Construction",
    tags: ["construction procurement", "material costs", "spend classification", "supplier consolidation"],
    readingTime: 8,
    tocItems: [
      { id: "structural-problem", label: "Why construction data is different" },
      { id: "steel-case-study", label: "Steel: a case study" },
      { id: "spec-standardisation", label: "Specification standardisation" },
      { id: "software-integration", label: "Integration with construction software" },
    ],
    tocItemsNl: [
      { id: "structural-problem", label: "Waarom bouwdata anders is" },
      { id: "steel-case-study", label: "Staal: een casestudy" },
      { id: "spec-standardisation", label: "Specificatiestandardisatie" },
      { id: "software-integration", label: "Integratie met bouwsoftware" },
    ],
    softCta: "case-study",
  },
  {
    slug: "what-clean-data-enables",
    image: "/images/blog/what-clean-data-enables.jpg",
    title: "What Happens When Your Data Is Finally Clean: 5 Things That Become Possible",
    description: "Five specific capabilities that open up when procurement and asset data is clean, classified, and consistently maintained with practical examples of what each looks like.",
    publishedAt: "2026-04-28",
    category: "Procurement",
    tags: ["procurement data quality", "asset management", "AI readiness", "tender pricing"],
    readingTime: 8,
    tocItems: [
      { id: "supplier-consolidation", label: "1. Supplier consolidation" },
      { id: "predictive-maintenance", label: "2. Predictive maintenance" },
      { id: "tender-pricing", label: "3. Accurate tender pricing" },
      { id: "ai-tools", label: "4. AI tools that deliver" },
      { id: "strategic-procurement", label: "5. Strategic procurement" },
    ],
    tocItemsNl: [
      { id: "supplier-consolidation", label: "1. Leveranciersconsolidatie" },
      { id: "predictive-maintenance", label: "2. Voorspellend onderhoud" },
      { id: "tender-pricing", label: "3. Nauwkeurige aanbestedingsprijzen" },
      { id: "ai-tools", label: "4. AI-tools die leveren" },
      { id: "strategic-procurement", label: "5. Strategische inkoop" },
    ],
    softCta: "case-study",
  },
  {
    slug: "unspsc-vs-eclass-vs-cpv",
    image: "/images/blog/unspsc-vs-eclass-vs-cpv.jpg",
    title: "UNSPSC vs. eClass vs. CPV: Which Classification Standard Is Right for Your Business?",
    description: "A clear breakdown of the three main procurement classification standards UNSPSC, eClass, and CPV with a practical guide to implementation at scale.",
    publishedAt: "2026-05-07",
    category: "Procurement",
    tags: ["UNSPSC", "eClass", "CPV", "procurement classification", "spend standards"],
    readingTime: 9,
    tocItems: [
      { id: "unspsc", label: "UNSPSC" },
      { id: "eclass", label: "eClass" },
      { id: "cpv", label: "CPV" },
      { id: "which-to-use", label: "Which to use" },
      { id: "implementation", label: "Implementation reality" },
    ],
    tocItemsNl: [
      { id: "unspsc", label: "UNSPSC" },
      { id: "eclass", label: "eClass" },
      { id: "cpv", label: "CPV" },
      { id: "which-to-use", label: "Welke te gebruiken" },
      { id: "implementation", label: "Implementatierealiteit" },
    ],
    softCta: "discovery",
    faqItems: [
      { q: "What is the difference between UNSPSC and eClass?", a: "UNSPSC is a global four-level taxonomy covering all products and services, best for spend analytics and category management. eClass includes product attribute definitions alongside codes, making it more precise for industrial and engineering master data." },
      { q: "Do I need to use CPV codes for private sector procurement?", a: "No. CPV is mandated only for EU public procurement notices. Private sector organisations should use UNSPSC or eClass for internal spend management." },
      { q: "How many UNSPSC codes are there?", a: "The UNSPSC taxonomy contains over 55,000 commodity codes across four levels: Segment, Family, Class, and Commodity. It is updated quarterly by GS1 US on behalf of the United Nations." },
    ],
  },
  {
    slug: "unspsc-classification-sap",
    image: "/images/blog/unspsc-classification-sap.jpg",
    title: "How to Implement UNSPSC Classification in SAP",
    description: "A practical guide to automating UNSPSC coding in SAP-based procurement environments — what works, what does not, and how to get from messy spend data to a clean category baseline.",
    publishedAt: "2026-04-14",
    category: "Procurement",
    tags: ["UNSPSC", "SAP", "procurement data quality", "spend classification"],
    readingTime: 8,
    tocItems: [
      { id: "sap-problem", label: "The SAP problem nobody talks about" },
      { id: "three-approaches", label: "Three approaches to UNSPSC in SAP" },
      { id: "what-to-export", label: "What data to export from SAP" },
      { id: "good-classification", label: "What good classification looks like" },
      { id: "review-queue", label: "The review queue" },
      { id: "timing", label: "Timing" },
    ],
    tocItemsNl: [
      { id: "sap-problem", label: "Het SAP-probleem waar niemand over spreekt" },
      { id: "three-approaches", label: "Drie benaderingen van UNSPSC in SAP" },
      { id: "what-to-export", label: "Welke data uit SAP te exporteren" },
      { id: "good-classification", label: "Hoe goede classificatie eruitziet" },
      { id: "review-queue", label: "De reviewwachtrij" },
      { id: "timing", label: "Timing" },
    ],
    softCta: "discovery",
  },
  {
    slug: "unspsc-classification-accuracy",
    image: "/images/blog/unspsc-classification-accuracy.jpg",
    title: "UNSPSC Classification Accuracy: What 90–95% Actually Means",
    description: "What does 90–95% automated UNSPSC classification accuracy mean in practice? How is it measured, what does the remaining 5–10% look like, and how does accuracy improve over time?",
    publishedAt: "2026-04-28",
    category: "Procurement",
    tags: ["UNSPSC", "procurement data quality", "classification accuracy", "data quality"],
    readingTime: 6,
    tocItems: [
      { id: "the-number", label: "The number you keep seeing" },
      { id: "how-measured", label: "How accuracy is defined" },
      { id: "hard-items", label: "What makes an item hard to classify" },
      { id: "accuracy-stages", label: "Accuracy at different stages" },
      { id: "four-layer", label: "How the four-layer engine works" },
      { id: "downstream", label: "What accuracy actually buys you" },
    ],
    tocItemsNl: [
      { id: "the-number", label: "Het getal dat u blijft zien" },
      { id: "how-measured", label: "Hoe nauwkeurigheid wordt gedefinieerd" },
      { id: "hard-items", label: "Wat een item moeilijk te classificeren maakt" },
      { id: "accuracy-stages", label: "Nauwkeurigheid in verschillende fasen" },
      { id: "four-layer", label: "Hoe de vierlaagsmotor werkt" },
      { id: "downstream", label: "Wat nauwkeurigheid u oplevert" },
    ],
    softCta: "discovery",
    faqItems: [
      { q: "What does 90–95% auto-classification mean?", a: "It means 90–95% of procurement line items are assigned a UNSPSC commodity code by the automated engine without any human input. The remaining 5–10% are flagged for human review." },
      { q: "How is UNSPSC accuracy measured?", a: "Accuracy is measured at commodity level — the most specific level of the UNSPSC hierarchy (8-digit code). Measuring at segment or family level would produce higher numbers but less useful classification." },
      { q: "Does accuracy improve over time?", a: "Yes. Every human review decision feeds back into the ML model. After 3 months of operation, auto-classification typically rises to 90–95%. After 12 months, it often exceeds 95% as the model learns from your team's decisions." },
    ],
  },
  {
    slug: "unspsc-for-mro",
    image: "/images/blog/unspsc-for-mro.jpg",
    title: "UNSPSC for MRO: Classifying Maintenance, Repair, and Operations Spend",
    description: "MRO procurement is the hardest category to classify consistently. Here is why UNSPSC works for maintenance spend, and what it takes to get clean MRO data from SAP or Maximo.",
    publishedAt: "2026-05-05",
    category: "Procurement",
    tags: ["UNSPSC", "MRO", "procurement data quality", "asset management", "maintenance"],
    readingTime: 7,
    tocItems: [
      { id: "why-hard", label: "Why MRO spend is the hardest to classify" },
      { id: "segments", label: "UNSPSC segments for MRO" },
      { id: "vs-mpn", label: "UNSPSC vs manufacturer part numbers" },
      { id: "how-it-works", label: "How automated MRO classification works" },
      { id: "enrichment", label: "Enriching to part number level" },
      { id: "downstream", label: "The downstream value" },
    ],
    tocItemsNl: [
      { id: "why-hard", label: "Waarom MRO-spend het moeilijkst te classificeren is" },
      { id: "segments", label: "UNSPSC-segmenten voor MRO" },
      { id: "vs-mpn", label: "UNSPSC vs fabrikantonderdeelnummers" },
      { id: "how-it-works", label: "Hoe geautomatiseerde MRO-classificatie werkt" },
      { id: "enrichment", label: "Verrijken tot onderdeelnummerniveau" },
      { id: "downstream", label: "De neerwaartse waarde" },
    ],
    softCta: "discovery",
  },
  {
    slug: "unspsc-category-management",
    image: "/images/blog/unspsc-category-management.jpg",
    title: "The Category Management Problem No One Talks About: Why You Need UNSPSC Spend Classification",
    description: "Category management in FM and infrastructure fails without commodity-level spend data. Learn how UNSPSC classification transforms unstructured invoice data into actionable procurement strategy.",
    publishedAt: "2026-05-18",
    category: "Procurement",
    tags: ["UNSPSC", "Category Management", "FM", "Infrastructure", "Spend Analysis"],
    readingTime: 7,
    tocItems: [
      { id: "the-category-management-problem", label: "The category management problem" },
      { id: "what-unspsc-makes-possible", label: "What UNSPSC makes possible" },
      { id: "before-after", label: "Before and after: a real example" },
      { id: "where-to-start", label: "Where to start" },
    ],
    tocItemsNl: [
      { id: "the-category-management-problem", label: "Het category management-probleem" },
      { id: "what-unspsc-makes-possible", label: "Wat UNSPSC mogelijk maakt" },
      { id: "before-after", label: "Voor en na: een echt voorbeeld" },
      { id: "where-to-start", label: "Waar te beginnen" },
    ],
    softCta: "discovery",
  },
  {
    slug: "maverick-spend-unspsc",
    image: "/images/blog/maverick-spend-unspsc.jpg",
    title: "How to Control Maverick Spend: Why It's a Data Problem, Not a Discipline Problem",
    description: "Discover why maverick spend in FM and construction is a data visibility issue, and how commodity-level UNSPSC classification can uncover hidden procurement savings.",
    publishedAt: "2026-05-18",
    category: "Procurement",
    tags: ["UNSPSC", "Maverick Spend", "Procurement", "MRO", "FM", "Spend Control"],
    readingTime: 7,
    tocItems: [
      { id: "maverick-spend-is-not-a-discipline-problem", label: "Not a discipline problem" },
      { id: "what-gets-exposed", label: "What gets exposed" },
      { id: "the-golden-500", label: "The Golden 500 SKU approach" },
      { id: "the-mro-case", label: "The MRO case" },
    ],
    tocItemsNl: [
      { id: "maverick-spend-is-not-a-discipline-problem", label: "Geen disciplineprobleem" },
      { id: "what-gets-exposed", label: "Wat wordt blootgelegd" },
      { id: "the-golden-500", label: "De Gouden 500 SKU-aanpak" },
      { id: "the-mro-case", label: "De MRO-casus" },
    ],
    softCta: "discovery",
  },
  {
    slug: "win-ai-race-procurement-data-quality",
    image: "/images/blog/win-ai-race-procurement-data-quality.jpg",
    title: "How to Win the AI Race in Procurement: Start with Clean Data",
    description: "AI in procurement only works when your data is clean, classified, and trusted. Learn how Pearstop helps hard services teams turn procurement and asset data into an AI-ready advantage.",
    publishedAt: "2026-06-11",
    category: "AI & Digital",
    tags: ["AI readiness", "procurement data quality", "data classification", "digital transformation"],
    readingTime: 9,
    tocItems: [
      { id: "the-problem-is-not-lack-of-data", label: "The problem is not lack of data" },
      { id: "ai-readiness-is-a-procurement-issue", label: "AI readiness is a procurement issue" },
      { id: "what-pearstop-does", label: "What Pearstop does" },
      { id: "why-classification-matters", label: "Why classification matters" },
      { id: "human-in-control-automation", label: "Human-in-control automation" },
      { id: "how-to-win-the-ai-race", label: "How to win the AI race" },
    ],
    tocItemsNl: [
      { id: "the-problem-is-not-lack-of-data", label: "Het probleem is niet een gebrek aan data" },
      { id: "ai-readiness-is-a-procurement-issue", label: "AI-gereedheid is een procurement-vraagstuk" },
      { id: "what-pearstop-does", label: "Wat Pearstop doet" },
      { id: "why-classification-matters", label: "Waarom classificatie belangrijk is" },
      { id: "human-in-control-automation", label: "Mens-in-controle-automatisering" },
      { id: "how-to-win-the-ai-race", label: "Hoe de AI-race te winnen" },
    ],
    softCta: "discovery",
  },
  {
    slug: "procurement-data-readiness-ai",
    image: "/images/blog/procurement-data-readiness-ai.jpg",
    title: "What Is Procurement Data Readiness, and Why Does It Matter for AI?",
    description: "Procurement data readiness is the foundation of AI in procurement. Learn what it means, why data quality matters, and how Pearstop helps hard services teams get AI-ready.",
    publishedAt: "2026-06-11",
    category: "AI & Digital",
    tags: ["AI readiness", "procurement data quality", "data readiness", "digital transformation"],
    readingTime: 8,
    tocItems: [
      { id: "why-procurement-data-is-often-difficult-to-use", label: "Why procurement data is difficult to use" },
      { id: "what-does-clean-procurement-data-look-like", label: "What clean procurement data looks like" },
      { id: "how-pearstop-supports-procurement-data-readiness", label: "How Pearstop supports data readiness" },
      { id: "why-ai-in-procurement-depends-on-data-quality", label: "Why AI depends on data quality" },
      { id: "how-organisations-can-win-the-ai-race-in-procurement", label: "How to win the AI race" },
      { id: "the-future-of-procurement-is-ai-ready-data", label: "The future of procurement" },
    ],
    tocItemsNl: [
      { id: "why-procurement-data-is-often-difficult-to-use", label: "Waarom procurement data moeilijk te gebruiken is" },
      { id: "what-does-clean-procurement-data-look-like", label: "Hoe schone procurement data eruitziet" },
      { id: "how-pearstop-supports-procurement-data-readiness", label: "Hoe Pearstop data readiness ondersteunt" },
      { id: "why-ai-in-procurement-depends-on-data-quality", label: "Waarom AI afhankelijk is van datakwaliteit" },
      { id: "how-organisations-can-win-the-ai-race-in-procurement", label: "Hoe de AI-race te winnen" },
      { id: "the-future-of-procurement-is-ai-ready-data", label: "De toekomst van procurement" },
    ],
    softCta: "discovery",
  },
  {
    slug: "fm-oil-price-procurement-margins",
    image: "/images/blog/procurement-data-cost.jpg",
    title: "How Better Procurement Data Helps Facilities Management Companies Protect Margins During Oil Price Volatility",
    description: "When oil prices rise, fuel surcharges quietly erode FM margins. Better procurement data gives teams the visibility to identify, challenge, and reduce those costs before they compound.",
    publishedAt: "2026-06-23",
    category: "Procurement",
    tags: ["procurement data", "facilities management", "oil price", "fuel surcharges", "margin protection", "supplier management"],
    readingTime: 6,
    tocItems: [
      { id: "why-are-oil-prices-affecting-procurement-companies", label: "Why oil prices affect procurement" },
      { id: "how-fuel-surcharges-reduce-margins-in-facilities-management", label: "How fuel surcharges reduce margins" },
      { id: "how-procurement-tools-help-companies-avoid-unnecessary-fuel-surcharges", label: "How procurement tools help" },
      { id: "increasing-margins-through-better-supplier-data", label: "Increasing margins with better data" },
      { id: "pearstop-smarter-data-management-for-procurement-teams", label: "Pearstop: smarter data management" },
      { id: "the-future-of-procurement-is-data-led-margin-protection", label: "The future of procurement" },
    ],
    tocItemsNl: [
      { id: "waarom-olieprijzen-inkoopbedrijven-raken", label: "Waarom olieprijzen inkoop raken" },
      { id: "hoe-brandstoftoeslagen-de-marges-in-facility-management-verlagen", label: "Hoe toeslagen marges verlagen" },
      { id: "hoe-inkoop-tools-bedrijven-helpen-onnodige-brandstoftoeslagen-te-vermijden", label: "Hoe inkooptools helpen" },
      { id: "marges-vergroten-met-betere-leveranciersdata", label: "Marges vergroten met betere data" },
      { id: "pearstop-slimmer-databeheer-voor-inkoopteams", label: "Pearstop: slimmer databeheer" },
      { id: "de-toekomst-van-inkoop-is-datagedreven-margebescherming", label: "De toekomst van inkoop" },
    ],
    softCta: "discovery",
  },
  {
    slug: "cleaning-invoices-dont-match-contract",
    image: "/images/blog/what-clean-data-enables.jpg",
    title: "Why Your Cleaning Contractor Invoices Never Match What You Agreed",
    description: "Cleaning spend is some of the messiest data in FM. Here's why invoices drift from the contract, and how to get data you can actually trust.",
    publishedAt: "2026-06-18",
    category: "Procurement",
    tags: ["cleaning contracts", "invoice reconciliation", "FM spend data", "soft services"],
    readingTime: 5,
    tocItems: [
      { id: "the-pattern-we-see-over-and-over", label: "The pattern we see over and over" },
      { id: "why-cleaning-spend-is-uniquely-hard-to-clean", label: "Why cleaning spend is uniquely hard to clean" },
      { id: "what-good-cleaning-spend-data-actually-looks-like", label: "What good cleaning spend data looks like" },
    ],
    tocItemsNl: [
      { id: "the-pattern-we-see-over-and-over", label: "Het patroon dat we steeds weer zien" },
      { id: "why-cleaning-spend-is-uniquely-hard-to-clean", label: "Waarom schoonmaakdata uniek moeilijk schoon te krijgen is" },
      { id: "what-good-cleaning-spend-data-actually-looks-like", label: "Hoe goede schoonmaakdata er echt uitziet" },
    ],
    softCta: "discovery",
  },
  {
    slug: "consumables-creep-cleaning-spend",
    image: "/images/blog/maverick-spend-unspsc.jpg",
    title: "The Hidden Cost of Consumables Creep in Cleaning Contracts",
    description: "Consumables spend in cleaning contracts rarely shows up as one bad invoice. It shows up as a trend nobody's watching. Here's how to catch it.",
    publishedAt: "2026-06-19",
    category: "Data Quality",
    tags: ["cleaning spend", "consumables", "invoice analysis", "FM contracts"],
    readingTime: 5,
    tocItems: [
      { id: "why-nobody-catches-it", label: "Why nobody catches it" },
      { id: "the-classification-problem-underneath-it", label: "The classification problem underneath it" },
      { id: "what-tracking-it-properly-reveals", label: "What tracking it properly reveals" },
    ],
    tocItemsNl: [
      { id: "why-nobody-catches-it", label: "Waarom niemand het opmerkt" },
      { id: "the-classification-problem-underneath-it", label: "Het classificatieprobleem daaronder" },
      { id: "what-tracking-it-properly-reveals", label: "Wat goede tracking laat zien" },
    ],
    softCta: "discovery",
  },
  {
    slug: "security-spend-data-quality",
    image: "/images/blog/category-management-kraljic-hard-fm.jpg",
    title: "Security Spend Looks Fine on Paper. Here's Why It Isn't.",
    description: "Security contracts are priced on headcount and hours. But real security spend includes overtime, callouts, and event cover that rarely gets classified the same way twice.",
    publishedAt: "2026-06-19",
    category: "Procurement",
    tags: ["security spend", "FM contracts", "invoice data", "spend classification"],
    readingTime: 5,
    tocItems: [
      { id: "the-base-contract-is-the-easy-part", label: "The base contract is the easy part" },
      { id: "why-overtime-and-callouts-hide-in-plain-sight", label: "Why overtime and callouts hide in plain sight" },
      { id: "what-happens-once-its-classified-properly", label: "What happens once it's classified properly" },
    ],
    tocItemsNl: [
      { id: "the-base-contract-is-the-easy-part", label: "Het basiscontract is het makkelijke deel" },
      { id: "why-overtime-and-callouts-hide-in-plain-sight", label: "Waarom overwerk en callouts onopgemerkt blijven" },
      { id: "what-happens-once-its-classified-properly", label: "Wat er gebeurt zodra het goed geclassificeerd is" },
    ],
    softCta: "discovery",
  },
  {
    slug: "catering-vending-spend-classification",
    image: "/images/blog/unspsc-category-management.jpg",
    title: "Catering and Vending Spend: The FM Category Nobody Classifies Properly",
    description: "Catering and vending contracts mix subsidy, consumables, and equipment maintenance under one supplier. Most FM teams have no clean view of what's actually being spent on what.",
    publishedAt: "2026-06-20",
    category: "Data Management",
    tags: ["catering spend", "vending", "FM data", "soft services classification"],
    readingTime: 5,
    tocItems: [
      { id: "one-supplier-four-different-cost-types", label: "One supplier, four different cost types" },
      { id: "why-vending-is-worse-not-better", label: "Why vending is worse, not better" },
      { id: "what-separating-these-categories-actually-enables", label: "What separating these categories actually enables" },
    ],
    tocItemsNl: [
      { id: "one-supplier-four-different-cost-types", label: "Één leverancier, vier verschillende kostentypen" },
      { id: "why-vending-is-worse-not-better", label: "Waarom automaten er nog slechter aan toe zijn" },
      { id: "what-separating-these-categories-actually-enables", label: "Wat het scheiden van deze categorieën echt oplevert" },
    ],
    softCta: "discovery",
  },
  {
    slug: "hvac-maintenance-invoice-reconciliation",
    image: "/images/blog/excel-heroics-hard-services.jpg",
    title: "Why HVAC Maintenance Invoices Are the Hardest FM Category to Reconcile",
    description: "HVAC spend mixes planned maintenance, parts, and emergency repairs into invoices that rarely map cleanly to the contract. Here's why, and what to do about it.",
    publishedAt: "2026-06-21",
    category: "Procurement",
    tags: ["HVAC", "maintenance invoices", "FM spend", "invoice reconciliation"],
    readingTime: 5,
    tocItems: [
      { id: "one-visit-three-cost-types", label: "One visit, three cost types" },
      { id: "why-this-split-actually-matters-financially", label: "Why this split actually matters financially" },
      { id: "what-clean-hvac-data-lets-you-do", label: "What clean HVAC data lets you do" },
    ],
    tocItemsNl: [
      { id: "one-visit-three-cost-types", label: "Eén bezoek, drie kostentypen" },
      { id: "why-this-split-actually-matters-financially", label: "Waarom dit onderscheid financieel zo belangrijk is" },
      { id: "what-clean-hvac-data-lets-you-do", label: "Wat schone HVAC-data je laat doen" },
    ],
    softCta: "discovery",
  },
  {
    slug: "ppm-mande-spend-visibility",
    image: "/images/blog/what-clean-data-enables.jpg",
    title: "M&E Contracts: What \"Planned Preventive Maintenance\" Actually Costs You",
    description: "PPM is supposed to reduce reactive spend over time. Most FM teams can't prove whether it does, because PPM and reactive M&E costs are never classified separately.",
    publishedAt: "2026-06-22",
    category: "Data Quality",
    tags: ["PPM", "planned maintenance", "M&E spend", "FM contracts"],
    readingTime: 5,
    tocItems: [
      { id: "the-assumption-everyone-makes", label: "The assumption everyone makes" },
      { id: "why-the-invoices-dont-help-you-check", label: "Why the invoices don't help you check" },
      { id: "what-happens-once-you-can-actually-see-the-split", label: "What happens once you can actually see the split" },
    ],
    tocItemsNl: [
      { id: "the-assumption-everyone-makes", label: "De aanname die iedereen maakt" },
      { id: "why-the-invoices-dont-help-you-check", label: "Waarom de facturen je niet helpen controleren" },
      { id: "what-happens-once-you-can-actually-see-the-split", label: "Wat er gebeurt zodra je het onderscheid echt kunt zien" },
    ],
    softCta: "discovery",
  },
  {
    slug: "reactive-maintenance-callout-spend",
    image: "/images/blog/fm-tender-win-rate.jpg",
    title: "Reactive Maintenance Callouts Are Quietly Wrecking Your FM Budget",
    description: "One-off callouts look small individually. Classified and totalled across a year, they're often the single biggest unplanned cost in a hard services contract.",
    publishedAt: "2026-06-23",
    category: "Procurement",
    tags: ["reactive maintenance", "callout spend", "FM budget", "hard services"],
    readingTime: 5,
    tocItems: [
      { id: "why-callouts-get-approved-without-much-scrutiny", label: "Why callouts get approved without much scrutiny" },
      { id: "why-nobody-sees-the-total-until-its-classified", label: "Why nobody sees the total until it's classified" },
      { id: "what-the-total-usually-reveals", label: "What the total usually reveals" },
    ],
    tocItemsNl: [
      { id: "why-callouts-get-approved-without-much-scrutiny", label: "Waarom callouts zonder veel controle worden goedgekeurd" },
      { id: "why-nobody-sees-the-total-until-its-classified", label: "Waarom niemand het totaal ziet totdat het geclassificeerd is" },
      { id: "what-the-total-usually-reveals", label: "Wat het totaal meestal laat zien" },
    ],
    softCta: "discovery",
  },
  {
    slug: "subcontractor-invoice-data-quality",
    image: "/images/blog/construction-procurement-material-costs.jpg",
    title: "Subcontractor Invoices Are the Weakest Link in Construction Spend Data",
    description: "Subcontractors invoice in their own format, at their own pace, with their own line-item logic. That inconsistency is where most construction cost visibility disappears.",
    publishedAt: "2026-06-24",
    category: "Data Quality",
    tags: ["subcontractors", "construction invoices", "spend data", "cost visibility"],
    readingTime: 5,
    tocItems: [
      { id: "why-subcontractor-invoices-vary-so-much", label: "Why subcontractor invoices vary so much" },
      { id: "what-this-inconsistency-actually-costs-you", label: "What this inconsistency actually costs you" },
      { id: "the-fix-isnt-asking-subcontractors-to-change", label: "The fix isn't asking subcontractors to change" },
    ],
    tocItemsNl: [
      { id: "why-subcontractor-invoices-vary-so-much", label: "Waarom onderaannemersfacturen zo sterk variëren" },
      { id: "what-this-inconsistency-actually-costs-you", label: "Wat deze inconsistentie je echt kost" },
      { id: "the-fix-isnt-asking-subcontractors-to-change", label: "De oplossing is niet onderaannemers vragen om te veranderen" },
    ],
    softCta: "discovery",
  },
  {
    slug: "construction-procurement-data-benchmarking",
    image: "/images/blog/procurement-data-cost.jpg",
    title: "Why Construction Procurement Data Breaks Every Time You Try to Benchmark It",
    description: "Every project prices materials and subcontractors differently. Benchmarking construction spend across projects requires classification most cost systems were never built to do.",
    publishedAt: "2026-06-24",
    category: "Construction",
    tags: ["construction procurement", "benchmarking", "spend classification", "project data"],
    readingTime: 5,
    tocItems: [
      { id: "every-project-starts-from-zero", label: "Every project starts from zero" },
      { id: "why-this-makes-benchmarking-pointless-without-classification", label: "Why this makes benchmarking pointless without classification" },
      { id: "what-real-benchmarking-unlocks", label: "What real benchmarking unlocks" },
    ],
    tocItemsNl: [
      { id: "every-project-starts-from-zero", label: "Elk project begint vanaf nul" },
      { id: "why-this-makes-benchmarking-pointless-without-classification", label: "Waarom dit benchmarken zinloos maakt zonder classificatie" },
      { id: "what-real-benchmarking-unlocks", label: "Wat echt benchmarken oplevert" },
    ],
    softCta: "discovery",
  },
  {
    slug: "fuel-plant-hire-surcharges-construction",
    image: "/images/blog/construction-procurement-material-costs.jpg",
    title: "Fuel and Plant Hire Surcharges: The Line Items Construction Firms Never Check",
    description: "Fuel and plant hire surcharges are often applied automatically and rarely challenged. Extracted and classified properly, they're one of the fastest wins in construction spend audits.",
    publishedAt: "2026-06-25",
    category: "Procurement",
    tags: ["construction spend", "surcharges", "plant hire", "spend audit"],
    readingTime: 5,
    tocItems: [
      { id: "why-surcharges-go-unchecked", label: "Why surcharges go unchecked" },
      { id: "why-they-compound-into-real-money", label: "Why they compound into real money" },
      { id: "what-extraction-and-classification-reveals", label: "What extraction and classification reveals" },
    ],
    tocItemsNl: [
      { id: "why-surcharges-go-unchecked", label: "Waarom toeslagen ongecontroleerd blijven" },
      { id: "why-they-compound-into-real-money", label: "Waarom ze zich opstapelen tot echt geld" },
      { id: "what-extraction-and-classification-reveals", label: "Wat extractie en classificatie laat zien" },
    ],
    softCta: "discovery",
  },
  {
    slug: "infrastructure-procurement-data-portability",
    image: "/images/blog/procurement-data-readiness-ai.jpg",
    title: "Why Infrastructure Procurement Data Doesn't Travel Between Projects",
    description: "Long-term infrastructure contracts generate huge amounts of spend data that gets locked inside individual project systems. Here's why that data almost never makes it to the next project.",
    publishedAt: "2026-06-26",
    category: "Data Management",
    tags: ["infrastructure procurement", "data portability", "project data", "spend visibility"],
    readingTime: 5,
    tocItems: [
      { id: "why-the-data-stays-trapped", label: "Why the data stays trapped" },
      { id: "the-cost-of-starting-from-zero-every-time", label: "The cost of starting from zero every time" },
      { id: "what-portability-actually-requires", label: "What portability actually requires" },
    ],
    tocItemsNl: [
      { id: "why-the-data-stays-trapped", label: "Waarom de data vastzit" },
      { id: "the-cost-of-starting-from-zero-every-time", label: "De kosten van elke keer vanaf nul beginnen" },
      { id: "what-portability-actually-requires", label: "Wat portabiliteit echt vereist" },
    ],
    softCta: "discovery",
  },
  {
    slug: "multi-site-infrastructure-classification",
    image: "/images/blog/unspsc-classification-accuracy.jpg",
    title: "Multi-Site Infrastructure Contracts and the Classification Problem Nobody Talks About",
    description: "Infrastructure contracts spanning multiple sites and multiple contractors generate spend data in as many formats as there are suppliers. Consistent classification is the only way to see the whole picture.",
    publishedAt: "2026-06-26",
    category: "Data Quality",
    tags: ["infrastructure contracts", "multi-site", "spend classification", "data quality"],
    readingTime: 5,
    tocItems: [
      { id: "why-fragmentation-is-the-default-state", label: "Why fragmentation is the default state" },
      { id: "why-site-level-reporting-isnt-enough", label: "Why site-level reporting isn't enough" },
      { id: "what-programme-level-classification-actually-enables", label: "What programme-level classification actually enables" },
    ],
    tocItemsNl: [
      { id: "why-fragmentation-is-the-default-state", label: "Waarom fragmentatie de standaard is" },
      { id: "why-site-level-reporting-isnt-enough", label: "Waarom rapportage op locatieniveau niet genoeg is" },
      { id: "what-programme-level-classification-actually-enables", label: "Wat classificatie op programmaniveau echt oplevert" },
    ],
    softCta: "discovery",
  },
  {
    slug: "infrastructure-contract-spend-visibility",
    image: "/images/blog/what-clean-data-enables.jpg",
    title: "What Good Spend Visibility Looks Like on a Long-Term Infrastructure Contract",
    description: "Most infrastructure spend visibility is retrospective and manual. Here's what it looks like when the data is classified properly from the start.",
    publishedAt: "2026-06-27",
    category: "Procurement",
    tags: ["infrastructure contracts", "spend visibility", "data classification", "procurement"],
    readingTime: 5,
    tocItems: [
      { id: "why-visibility-usually-arrives-too-late", label: "Why visibility usually arrives too late" },
      { id: "what-continuous-classification-changes", label: "What continuous classification changes" },
      { id: "what-this-actually-looks-like-in-practice", label: "What this actually looks like in practice" },
    ],
    tocItemsNl: [
      { id: "why-visibility-usually-arrives-too-late", label: "Waarom visibiliteit meestal te laat komt" },
      { id: "what-continuous-classification-changes", label: "Wat continue classificatie verandert" },
      { id: "what-this-actually-looks-like-in-practice", label: "Hoe dit er in de praktijk uitziet" },
    ],
    softCta: "discovery",
  },
  {
    slug: "mro-spend-classification",
    image: "/images/blog/unspsc-for-mro.jpg",
    title: "MRO Spend Is the Most Under-Classified Category in Facilities Management",
    description: "Maintenance, repair, and operations spend covers everything from spare parts to consumables to emergency purchases. Most of it never gets classified consistently enough to manage.",
    publishedAt: "2026-06-28",
    category: "Data Quality",
    tags: ["MRO", "spend classification", "facilities management", "data quality"],
    readingTime: 5,
    tocItems: [
      { id: "why-mro-gets-ignored", label: "Why MRO gets ignored" },
      { id: "why-low-value-doesnt-mean-low-impact", label: "Why low value doesn't mean low impact" },
      { id: "what-classification-unlocks-even-at-this-scale", label: "What classification unlocks even at this scale" },
    ],
    tocItemsNl: [
      { id: "why-mro-gets-ignored", label: "Waarom MRO genegeerd wordt" },
      { id: "why-low-value-doesnt-mean-low-impact", label: "Waarom lage waarde niet lage impact betekent" },
      { id: "what-classification-unlocks-even-at-this-scale", label: "Wat classificatie oplevert, ook op deze schaal" },
    ],
    softCta: "discovery",
  },
  {
    slug: "mro-parts-vs-invoice-data-mismatch",
    image: "/images/blog/unspsc-classification-sap.jpg",
    title: "Why Your MRO Parts Data Never Matches Your MRO Invoice Data",
    description: "The parts recorded in your maintenance system and the parts billed on your invoices are often two different datasets that were never designed to talk to each other.",
    publishedAt: "2026-06-28",
    category: "Data Management",
    tags: ["MRO", "parts data", "invoice data", "maintenance systems"],
    readingTime: 5,
    tocItems: [
      { id: "two-systems-two-versions-of-the-truth", label: "Two systems, two versions of the truth" },
      { id: "why-this-gap-matters-more-than-it-seems", label: "Why this gap matters more than it seems" },
      { id: "what-matching-them-actually-requires", label: "What matching them actually requires" },
    ],
    tocItemsNl: [
      { id: "two-systems-two-versions-of-the-truth", label: "Twee systemen, twee versies van de waarheid" },
      { id: "why-this-gap-matters-more-than-it-seems", label: "Waarom dit gat meer betekent dan het lijkt" },
      { id: "what-matching-them-actually-requires", label: "Wat het matchen echt vereist" },
    ],
    softCta: "discovery",
  },
  {
    slug: "asset-data-vs-spend-data-mismatch",
    image: "/images/blog/asset-register-problems.jpg",
    title: "Why Asset Data and Spend Data Never Agree With Each Other",
    description: "Your asset register says one thing. Your maintenance spend says another. Here's why these two datasets almost always disagree, and why that gap matters.",
    publishedAt: "2026-06-29",
    category: "Asset Management",
    tags: ["asset data", "spend data", "data reconciliation", "maintenance"],
    readingTime: 5,
    tocItems: [
      { id: "two-datasets-built-by-two-different-worlds", label: "Two datasets, built by two different worlds" },
      { id: "what-happens-when-they-disagree", label: "What happens when they disagree" },
      { id: "why-reconciling-them-changes-decisions", label: "Why reconciling them changes decisions" },
    ],
    tocItemsNl: [
      { id: "two-datasets-built-by-two-different-worlds", label: "Twee datasets, gebouwd door twee verschillende werelden" },
      { id: "what-happens-when-they-disagree", label: "Wat er gebeurt als ze het niet eens zijn" },
      { id: "why-reconciling-them-changes-decisions", label: "Waarom reconciliëren beslissingen verandert" },
    ],
    softCta: "discovery",
  },
  {
    slug: "emergency-mro-purchases-spend-control",
    image: "/images/blog/maverick-spend-unspsc.jpg",
    title: "Emergency MRO Purchases Are Where Procurement Discipline Goes to Die",
    description: "Emergency parts and consumables purchases skip the normal procurement process by design. That's necessary, but it also means almost none of that spend gets classified or reviewed.",
    publishedAt: "2026-06-29",
    category: "Procurement",
    tags: ["MRO", "emergency purchasing", "spend control", "procurement discipline"],
    readingTime: 5,
    tocItems: [
      { id: "why-the-exception-has-to-exist", label: "Why the exception has to exist" },
      { id: "why-the-exception-becomes-a-blind-spot", label: "Why the exception becomes a blind spot" },
      { id: "what-reviewing-it-after-the-fact-reveals", label: "What reviewing it after the fact reveals" },
    ],
    tocItemsNl: [
      { id: "why-the-exception-has-to-exist", label: "Waarom de uitzondering moet bestaan" },
      { id: "why-the-exception-becomes-a-blind-spot", label: "Waarom de uitzondering een blinde vlek wordt" },
      { id: "what-reviewing-it-after-the-fact-reveals", label: "Wat het achteraf beoordelen laat zien" },
    ],
    softCta: "discovery",
  },
  {
    slug: "ai-procurement-data-classification-reality",
    image: "/images/blog/win-ai-race-procurement-data-quality.jpg",
    title: "Can AI Actually Classify Procurement Data, or Is That Still a Myth?",
    description: "Every procurement platform claims AI classification now. Here's what it can genuinely do today, and where it still needs a human check.",
    publishedAt: "2026-06-30",
    category: "AI & Digital",
    tags: ["AI classification", "procurement data", "automation", "data quality"],
    readingTime: 5,
    tocItems: [
      { id: "what-ai-genuinely-does-well", label: "What AI genuinely does well" },
      { id: "where-it-still-struggles", label: "Where it still struggles" },
      { id: "how-to-tell-if-a-vendors-claim-is-real", label: "How to tell if a vendor's claim is real" },
    ],
    tocItemsNl: [
      { id: "what-ai-genuinely-does-well", label: "Waar AI echt goed in is" },
      { id: "where-it-still-struggles", label: "Waar het nog moeite mee heeft" },
      { id: "how-to-tell-if-a-vendors-claim-is-real", label: "Hoe je weet of de claim van een leverancier echt is" },
    ],
    softCta: "discovery",
  },
  {
    slug: "commercial-fm-contract-billing-mismatch",
    image: "/images/blog/fm-tender-win-rate.jpg",
    title: "Why Commercial FM Contracts Are Priced for One Reality and Billed for Another",
    description: "Commercial FM contracts are negotiated against a defined scope. The invoices that follow rarely reflect that scope cleanly, across any service line.",
    publishedAt: "2026-07-01",
    category: "Commercial FM",
    tags: ["commercial FM", "contract billing", "invoice reconciliation", "spend data"],
    readingTime: 5,
    tocItems: [
      { id: "the-moment-the-contract-and-reality-start-to-diverge", label: "The moment the contract and reality start to diverge" },
      { id: "why-nobody-notices-until-its-a-big-number", label: "Why nobody notices until it's a big number" },
      { id: "what-checking-billed-reality-against-contracted-scope-requires", label: "What checking billed reality against contracted scope requires" },
    ],
    tocItemsNl: [
      { id: "the-moment-the-contract-and-reality-start-to-diverge", label: "Het moment waarop contract en realiteit beginnen te divergeren" },
      { id: "why-nobody-notices-until-its-a-big-number", label: "Waarom niemand het opmerkt totdat het een groot getal is" },
      { id: "what-checking-billed-reality-against-contracted-scope-requires", label: "Wat het controleren van gefactureerde realiteit tegen gecontracteerde scope vereist" },
    ],
    softCta: "discovery",
  },
  {
    slug: "datore-vs-pearstop",
    title: "Datore vs Pearstop: Two Different Ways to Turn Messy Business Data into Action",
    description: "Datore and Pearstop both help businesses in the built environment tackle messy operational data — but from different angles. Here is how they compare and where each one fits.",
    publishedAt: "2026-06-19",
    category: "Data Quality",
    tags: ["data quality", "procurement data", "facilities management", "built environment", "data strategy"],
    readingTime: 6,
    tocItems: [
      { id: "what-datore-does", label: "What Datore does" },
      { id: "what-pearstop-does", label: "What Pearstop does" },
      { id: "datores-strength-is-breadth", label: "Datore's strength is breadth" },
      { id: "pearstops-strength-is-depth", label: "Pearstop's strength is depth" },
      { id: "where-they-sit-in-the-data-value-chain", label: "Where they sit in the data value chain" },
      { id: "how-to-choose", label: "How to choose" },
      { id: "two-complementary-layers-of-the-same-journey", label: "Two complementary layers" },
    ],
    softCta: "discovery",
    hidden: true,
  },
  {
    slug: "eu-ai-act-compliance-data-quality",
    image: "/images/blog/procurement-data-cost.jpg",
    title: "Compliant by Design: How Pearstop Answers the EU AI Act's Data Obligations",
    description: "The EU AI Act's latest obligations took effect on 2 August 2026. Meeting them starts with data that is clean, categorised, and auditable — here's how Pearstop gets you there.",
    publishedAt: "2026-08-17",
    category: "AI & Digital",
    tags: ["EU AI Act", "AI compliance", "data quality", "audit trail"],
    readingTime: 6,
    tocItems: [
      { id: "what-just-happened-the-eu-ai-act-context", label: "What just happened" },
      { id: "consequences-of-non-compliance", label: "Consequences of non-compliance" },
      { id: "enter-pearstop-compliance-isnt-one-feature-its-the-whole-platform", label: "How Pearstop maps to the obligations" },
      { id: "the-pearstop-value-proposition", label: "The value proposition" },
      { id: "frequently-asked-questions", label: "FAQ" },
    ],
    tocItemsNl: [
      { id: "wat-is-er-net-veranderd-de-context-van-de-eu-ai-act", label: "Wat is er net veranderd" },
      { id: "gevolgen-van-niet-naleving", label: "Gevolgen van niet-naleving" },
      { id: "pearstop-als-antwoord-compliance-is-geen-losse-feature-maar-het-hele-platform", label: "Hoe Pearstop aansluit op de verplichtingen" },
      { id: "de-waardepropositie-van-pearstop", label: "De waardepropositie" },
      { id: "veelgestelde-vragen", label: "Veelgestelde vragen" },
    ],
    softCta: "discovery",
    faqItems: [
      {
        q: "What EU AI Act obligations came into effect on 2 August 2026?",
        a: "The latest wave covers high-risk system obligations and most remaining general obligations under the Act, building on provisions already in force since 2024 and 2025, including prohibited practices, GPAI provider duties, and transparency requirements.",
      },
      {
        q: "What are the penalties for non-compliance with the EU AI Act?",
        a: "Article 99 sets three tiers: up to €35 million or 7% of global turnover for prohibited practices, up to €15 million or 3% for non-compliance with high-risk requirements and most other obligations, and up to €7.5 million or 1% for supplying incorrect, incomplete, or misleading information to authorities or notified bodies. In every tier, whichever figure is higher applies.",
      },
      {
        q: "How does Pearstop help with EU AI Act compliance?",
        a: "Pearstop classifies and structures procurement and asset data with built-in audit trails and quality checks, so the traceability the Act requires is a by-product of data cleanup work you're already doing, rather than a separate compliance project.",
      },
      {
        q: "Is compliance only relevant to companies building AI systems?",
        a: "No. Deployers and users of AI systems carry obligations too, particularly around transparency and high-risk system documentation, so the requirement to show clean, traceable data applies broadly across the supply chain, not just to AI providers.",
      },
    ],
  },
  {
    slug: "how-to-build-a-spend-cube-with-ai",
    image: "/images/blog/how-to-build-a-spend-cube-with-ai.jpg",
    title: "How to build a spend cube with AI",
    description: "The five steps to building a spend cube, what data you need, what usually goes wrong, and when a consultant is a better choice than an AI classification pipeline.",
    publishedAt: "2026-08-25",
    category: "AI & Digital",
    tags: ["spend cube", "spend analysis", "AI classification", "procurement data"],
    readingTime: 9,
    tocItems: [
      { id: "what-a-spend-cube-actually-is", label: "What a spend cube actually is" },
      { id: "building-a-spend-cube-step-by-step", label: "Building a spend cube step by step" },
      { id: "when-to-use-a-procurement-consultant", label: "When to use a procurement consultant" },
      { id: "when-to-use-an-ai-pipeline", label: "When to use an AI pipeline" },
      { id: "frequently-asked-questions", label: "FAQ" },
    ],
    softCta: "discovery",
    faqItems: [
      {
        q: "What is a spend cube in procurement?",
        a: "A spend cube is procurement spend organised across several dimensions at once, so it can be sliced from any angle. The standard dimensions are supplier, category and business unit or cost centre, with time as a fourth. It answers who bought what, from whom, and when, without anyone rebuilding a spreadsheet each time.",
      },
      {
        q: "What data do you need to build a spend cube?",
        a: "You need line-level transaction data, not summary totals. The minimum useful export contains a document number, a date, a supplier name and number, the free-text line description, quantity, unit price, total value, currency, and a cost centre or entity reference. An internal material or product number, where one exists, materially improves accuracy.",
      },
      {
        q: "How long does it take to build a spend cube?",
        a: "A pilot on around one year of data takes roughly four weeks, including time to review findings and adjust the classification rules before the full run. Extracting and cleaning the source data is usually the slowest part and depends on the finance team, not the classification method. A full historical backlog follows once the rules are settled.",
      },
      {
        q: "Is it cheaper to build a spend cube with AI or a consultant?",
        a: "AI is cheaper for the classification work and cheaper again for keeping the cube current, because the marginal cost of the next month of data is close to zero. A consultant costs more per exercise but includes negotiation strategy and execution support that a pipeline does not provide. The two solve different problems.",
      },
      {
        q: "Can ChatGPT or Copilot classify procurement spend data?",
        a: "Not reliably at scale. General assistants invent category codes that do not exist in the taxonomy, classify the same description differently across runs, and give no indication of how confident they are. They are useful for exploring a few hundred lines. They do not produce the repeatability a spend cube depends on.",
      },
      {
        q: "How does Pearstop build a spend cube?",
        a: "Pearstop ingests line-level data, resolves the supplier list against a reference database, applies a constrained taxonomy so codes cannot be invented, encodes the rules agreed with the procurement team, and routes low-confidence lines to human review. Corrections feed back into the pipeline, and the cube updates as new data arrives rather than being rebuilt.",
      },
    ],
  },
  {
    slug: "unspsc-classification-construction-guide",
    image: "/images/blog/unspsc-classification-construction-guide.jpg",
    title: "UNSPSC classification in construction: a practical guide",
    description: "How construction and engineering teams apply UNSPSC to procurement data, who owns the decisions, how to handle edge cases, and where AI actually fits.",
    publishedAt: "2026-08-25",
    category: "Procurement",
    tags: ["UNSPSC", "construction procurement", "spend classification", "category management"],
    readingTime: 9,
    tocItems: [
      { id: "unspsc-explained-in-four-levels", label: "UNSPSC explained in four levels" },
      { id: "who-owns-unspsc-classification-decisions", label: "Who owns UNSPSC classification decisions" },
      { id: "how-to-handle-unspsc-edge-cases", label: "How to handle UNSPSC edge cases" },
      { id: "using-ai-for-unspsc-classification", label: "Using AI for UNSPSC classification" },
      { id: "frequently-asked-questions", label: "FAQ" },
    ],
    softCta: "template",
    faqItems: [
      {
        q: "What does UNSPSC stand for?",
        a: "UNSPSC stands for United Nations Standard Products and Services Code. It is a classification system designed as a single standard for procurement worldwide. It covers goods and services across every industry, including construction, manufacturing and facilities management, and organises them into a four-level hierarchy running from a broad segment down to an individual commodity.",
      },
      {
        q: "How many levels does UNSPSC have?",
        a: "UNSPSC has four levels: segment, family, class and commodity. Segment is the broadest grouping, such as structures and building components. Commodity is the individual item, such as an aluminium I profile. Most organisations classify to family or class level for reporting and only go to commodity level where a specific category is being actively negotiated.",
      },
      {
        q: "Is UNSPSC suitable for construction procurement?",
        a: "Yes. UNSPSC expands into construction-specific branches covering structural elements, building materials, HVAC equipment and subcontracted services. Because the standard is used across industries and borders, suppliers and clients often already hold codes against their own catalogues. That makes it easier to compare spend externally than a taxonomy built in-house for one company.",
      },
      {
        q: "Can AI classify purchase orders to UNSPSC codes accurately?",
        a: "It can, but not with a general-purpose chatbot alone. Language models invent codes that do not exist in the taxonomy, which destroys the repeatability the exercise depends on. Accurate classification requires the taxonomy loaded as a constrained reference, supplier context weighted against the line description, company-specific rules, and a review step for low-confidence lines.",
      },
      {
        q: "How long does it take to classify a backlog of purchase orders?",
        a: "A pilot on roughly one year of data takes about four weeks, which allows time to build the structures, review initial findings and adjust the rules. A full historical backlog runs after the pilot, and the timeline depends on how much custom configuration the data needs rather than on the number of lines involved.",
      },
      {
        q: "How does Pearstop handle UNSPSC classification?",
        a: "Pearstop loads the UNSPSC taxonomy as a constrained reference so codes cannot be invented, weights supplier context against the line description, applies company-specific rules agreed with the procurement team, and routes low-confidence lines to human review. Corrections feed back into the pipeline so the same ambiguous line does not need deciding twice.",
      },
    ],
  },
  {
    slug: "manufacturing-procurement-sap-data-quality",
    image: "/images/blog/manufacturing-procurement-sap-data-quality.jpg",
    title: "Manufacturing procurement data: the SAP problem hard FM already solved",
    description: "95% of manufacturing spend auto-classified, without touching the SAP structure underneath it.",
    publishedAt: "2026-08-27",
    category: "Procurement",
    tags: ["manufacturing procurement", "SAP data quality", "spend classification", "supplier data", "master data"],
    readingTime: 5,
    tocItems: [
      { id: "why-manufacturers-assume-this-is-a-data-problem", label: "Why this looks like a data problem" },
      { id: "what-does-unclassified-spend-actually-cost", label: "What unclassified spend costs" },
      { id: "who-is-responsible-for-fixing-it", label: "Who is responsible for fixing it" },
      { id: "what-this-looks-like-on-a-real-sap-export", label: "What this looks like on a real SAP export" },
      { id: "why-not-just-point-a-general-ai-tool-at-the-export", label: "Why not a general AI tool" },
      { id: "what-the-first-step-actually-looks-like", label: "What the first step looks like" },
    ],
    softCta: "discovery",
    faqItems: [
      { q: "Why does a manufacturer with years of SAP history still have unclassified spend data?", a: "Because item descriptions vary by whoever entered the purchase order, supplier names drift across plants, and categories were set up locally when the ERP was configured. It is a structure problem, not a missing data problem: the transactions exist, but nobody built the taxonomy that lets anyone query them consistently." },
      { q: "How much does poor master data cost manufacturers?", a: "Poor master data costs organisations an average of 12.9 million dollars a year. For manufacturers running material master records across multiple plants and ERP instances, the same part often exists under several different material numbers, producing duplicate purchase orders and redundant inventory." },
      { q: "What accuracy do legacy classification tools typically achieve on spend data?", a: "Legacy classification tools generally land at 75 to 85 percent accuracy on structured spend. The remaining 15 to 25 percent is usually tail spend, services, and P-card transactions, which is exactly where supplier consolidation and price benchmarking would help most." },
      { q: "What are the steps to classify unstructured SAP procurement data?", a: "Three steps: resolve the supplier list to find duplicate suppliers bought under different names, apply a constrained taxonomy so a part cannot be given a category outside the standard, then classify every line and route uncertain cases to a person through confidence scoring." },
      { q: "Why not use a general AI tool to classify SAP spend data instead?", a: "A general-purpose model invents category codes that do not exist in your taxonomy and classifies the same description differently across runs, so it produces an answer but not a repeatable one. On a live SAP feed that needs to stay accurate as new purchase orders land daily, that inconsistency is not tolerable." },
      { q: "How does Pearstop classify manufacturing procurement data in SAP?", a: "Pearstop resolves the supplier list, applies a constrained taxonomy, encodes the categorisation rules the procurement team already uses, and classifies the backlog. On one mid-sized manufacturer's SAP export, this auto-classified 95 percent of lines directly against the existing SAP structure." },
    ],
  },
];

export const blogPosts: BlogPost[] = _allBlogPosts.filter((p) => !p.hidden);

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
